server:
  port: ${SERVER_PORT:5200}
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: security-admin
  # 数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:192.168.25.201}:${DB_PORT:5432}/${DB_NAME:security}?characterEncoding=utf8&useSSL=false
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}

    # Druid连接池配置
    #    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化
      initial-size: 3
      # 最大
      max-active: 300
      # 最小
      min-idle: 3
      # 最大连接等待超时时间
      max-wait: 60000
      # 打开PSCache,并且指定每个连接PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间,单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:192.168.25.201}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 1000ms
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.qitech.mybatis.entity  # 注意：对应实体类的路径
#pagehelper分页插件
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  instance:
    hostname: security-admin-${random.value}
    instance-id: ${eureka.instance.hostname}:${server.port}:@project.version@
    ip-address: ${INSTANCE_IP:192.168.25.201}
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    lease-expiration-duration-in-seconds: 2
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30S
    lease-renewal-interval-in-seconds: 1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:192.168.25.201}:${EUREKA_PORT:8761}/eureka/
    healthcheck:
      enable: true
    ##eureka client刷新本地缓存时间
    # 默认30s
    registryFetchIntervalSeconds: 5

ribbon:
  #eureka客户端ribbon刷新时间
  ServerListRefreshInterval: 5000
  # 默认的调用超时时间
  ConnectTimeout: 500
  ReadTimeout: 5000

druid:
  allow:
  deny:
  loginUsername: admin
  loginPassword: show@me@the@money
  resetEnable: false

logging:
  config: classpath:config/logback-hn.xml
  # 打印sql
  level:
    com.qitech.mybatis.mapper : debug
